### ISSUE TITLE
About UN1CA 2.0 for Samsung A71 ! Very important !

### ISSUE THREAD

**Issue by bigle30** [salvogiangri/UN1CA#105]
Hey Salvo! Great seeing you again in action! I really missed you!

Perhaps you remember me as AOSP ROM builder for A71?

As you might know that I've been banned from unica group on telegram for unknown reasons until now! I didn't know before that reaching any mods/devs via telegram can cause this! I was just reporting bugs!

Anyway, what I really want to mention that the old version was missing apps, for example the Samsung keyboard has grayed out options.
Also, the old un1ca have broken google assistant due to missing velvet app. I already mentioned this before in UN1CA group on telegram.
Also, Facebook Stories randomly stops playing and that tried it too many times on stock or asp works fine but on un1ca 1.1.6 just stops.

Again thanks for your efforts, time and making our devices valuable again after Samsung ditching us.

**Comment by salvogiangri** [comment]
> Hey Salvo! Great seeing you again in action! I really missed you!

❤️

> for example the Samsung keyboard has grayed out options.

Mind mentioning which ones?

> Also, the old un1ca have broken google assistant due to missing velvet app. I already mentioned this before in UN1CA group on telegram.

This is fake. The Google app hasn't been debloated in the ROM in any device. Perhaps you flashed an unofficial build?

> Also, Facebook Stories randomly stops playing and that tried it too many times on stock or asp works fine but on un1ca 1.1.6 just stops.

Wait for 2.0.0 and report if the issue is still there.

**Comment by bigle30** [comment]
just for more details :

> Also, the old un1ca have broken google assistant due to missing velvet app. I already mentioned this before in UN1CA group on telegram.

for this one exactly, the google assistant voice command "ok google" does work first , after updating apps via google play store, it doesn't respond anymore.
