### ISSUE TITLE
Google assistant/Bixby voice command issue on UN1CA 2.0

### ISSUE THREAD

**Issue by bigle30** [salvogiangri/UN1CA#107]
hello, i'm A71 user. i used UN1CA 2.0.0 today, flashed correctly and updated apps via google play store. when i used google assisstant, the wakeup command "ok google" doesn't work. same case for bixby saying "hi bixby" does not work either.

**Comment by bigle30** [comment]
also i can't reach un1ca telegram channel because i was banned ! for no reason !

**Comment by salvogiangri** [comment]
Fixed, the fix will be available in the next release. Thanks for reporting.
