### ISSUE TITLE
wifi nao liga no m52 com binary 5

### ISSUE THREAD

**Issue by Uzem52** [salvogiangri/UN1CA#111]
### UN1CA version:

2.0.0-07d0046

### Device name:

galaxy m52

### Device model number:

SM-M526B

### Magisk/KernelSU version:

nao coloquei

### Steps to reproduce:

wifi nao suportado no binary 5

### Expected behaviour:

Que funcionasse o wifi corretamente

### Actual behaviour:

nao funcionou

https://github.com/salvogiangri/UN1CA/assets/173009571/45c0d5d7-bd97-41dc-8c6b-1e62a904ad63

### Logs:

![Screenshot_20240616_235149_Settings](https://github.com/salvogiangri/UN1CA/assets/173009571/529d7a84-454e-4312-8434-0139392d8ca2)

**Comment by salvogiangri** [comment]
Fixed in 2.0.1 release.
