### ISSUE TITLE
usb file transfer doesn't work 

### ISSUE THREAD

**Issue by hsheemi** [salvogiangri/UN1CA#113]
### UN1CA version:

2.0.1-0553b05 (Eureka)

### Device name:

Galaxy M52 5g

### Device model number:

SM-M526BR/DS

### Magisk/KernelSU version:

ksu 0.9.4
![usb](https://github.com/salvogiangri/UN1CA/assets/84259305/f6977bf6-9314-40fc-b920-29ec09a2fccf)

### Steps to reproduce:

...

### Expected behaviour:

Windows 11 should detect phone storage when usb is connected 

### Actual behaviour:

Windows 11 doesn't detect phone storage when usb is connected for file transferring 

### Logs:

[logs-2024-06-18-06-21-34.zip](https://github.com/user-attachments/files/15880005/logs-2024-06-18-06-21-34.zip)

**Comment by hsheemi** [comment]
I think usb file transfer worked in unica 1.1.6

**Comment by salvogiangri** [comment]
> [logs-2024-06-18-06-21-34.zip](https://github.com/user-attachments/files/15880005/logs-2024-06-18-06-21-34.zip)

Nothing relevant in the logs. Avoid using in-device third party apps to capture them and instead use adb.

**Comment by hsheemi** [comment]
> > [logs-2024-06-18-06-21-34.zip](https://github.com/user-attachments/files/15880005/logs-2024-06-18-06-21-34.zip)
> 
> Nothing relevant in the logs. Avoid using in-device third party apps to capture them and instead use adb.

I'm so sorry,  it worked fine after choosing mtp usb Device from Device manager,  sorry again and many thanks for your hard work 💜
