### ISSUE TITLE
AOD brightness

### ISSUE THREAD

**Issue by JasimAlrawie** [salvogiangri/UN1CA#114]
### UN1CA version:

2.0.1

### Device name:

A52 4g

### Device model number:

SM-A525F

### Magisk/KernelSU version:

KernelSU 4.14.190-Ascendia-14.0-v3.2.2-o-KSU
manger: v1.0.0

### Steps to reproduce:

123

### Expected behaviour:

AOD brightness 

### Actual behaviour:

The AOD brightness is so low that it's barely visible.

### Logs:

:)

**Comment by Fede2782** [comment]
Hi, since One UI 6.1 the AoD brightness can be regulated via the GoodLock Module called LockStar. Maybe you can fix your issue by regulating the brightness manually. Even on my stock A35 since One UI 6.1 the automatic brightness is never enough to be able to see it.


![Screenshot_20240619_101854_LockStar](https://github.com/salvogiangri/UN1CA/assets/78815152/ace2c1e4-59e0-4daf-be75-72461a4a5235)

**Comment by JasimAlrawie** [comment]
> Hi, since One UI 6.1 the AoD brightness can be regulated via the GoodLock Module called LockStar. Maybe you can fix your issue by regulating the brightness manually. Even on my stock A35 since One UI 6.1 the automatic brightness is never enough to be able to see it.
> 
> ![Screenshot_20240619_101854_LockStar](https://private-user-images.githubusercontent.com/78815152/340987305-ace2c1e4-59e0-4daf-be75-72461a4a5235.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzEwODYsIm5iZiI6MTcxODgzMDc4NiwicGF0aCI6Ii83ODgxNTE1Mi8zNDA5ODczMDUtYWNlMmMxZTQtNTllMC00ZGFmLWJlNzUtNzI0NjFhNGE1MjM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIwNTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNjMyZTliNTliY2I1NzIxODU1MmNjNWU5YjMwZWZhZmE5YTNiYjllZDk1OTkwOGRkNDFlMTRmNDNlZTMyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xIprSNZwmGho2k0OeCRIvRA3tj4PbwxqEef7IcmniAE)

i dont have this option :)

**Comment by salvogiangri** [comment]
I'm gonna have to remove the AOD wallpaper feature starting from the next release as there's more disadvantages than benefits by having it. Closing the issue.
