### ISSUE TITLE
A71 : sound cut off completely and device start lags when playing videos

### ISSUE THREAD

**Issue by bigle30** [salvogiangri/UN1CA#116]
### UN1CA version:

UN1CA_2.0.1-0553b05

### Device name:

Galaxy A71

### Device model number:

SM-A715F/DS

### Magisk/KernelSU version:

Magisk with following modules included : zygisk-detach, Play Integrity fix v16.0
No custom kernels have been used.

### Steps to reproduce:

1. playing music throw samsung music app
2. playing facebook reels randomly
3. 
[video_2024-06-19_20-06-13.zip](https://github.com/user-attachments/files/15905141/video_2024-06-19_20-06-13.zip)

### Expected behaviour:

music and video should play normally

### Actual behaviour:

what actually happens that there is no sound at all on the device and playing video lags when playing any video contient, this happens randomly and often repeats.
the only temporally solution to this, is to reboot the device but as i said it repeats often.

### Logs:

[Log_2024-06-19_17-39-22.txt](https://github.com/user-attachments/files/15905165/Log_2024-06-19_17-39-22.txt)

**Comment by bigle30** [comment]
3 days until now, does my report seems irrelevant ?

**Comment by SecureChocolate879** [comment]
> 3 days until now, does my report seems irrelevant ?

No, I had the same issue with my Samsung A71 as well. Every time I watch a reel on Instagram or YouTube, it would always lags the whole video and it's kinda annoying.

**Comment by bigle30** [comment]
> No, I had the same issue with my Samsung A71 as well. Every time I watch a reel on Instagram or YouTube, it would always lag and it's kinda annoying.
you can provide a logcat ?

**Comment by salvogiangri** [comment]
Closing this for now with the 2.1.0 release. If this still happens, feel free to reopen it.
