### ISSUE TITLE
[ISSUE] Phone model is not correct

### ISSUE THREAD

**Issue by SMorganYu** [salvogiangri/UN1CA#117]
### UN1CA version:

2.0.1

### Device name:

Galaxy A73 5G

### Device model number:

SM-A736B

### Magisk/KernelSU version:

Magisk Kitsune 27

### Steps to reproduce:

-

### Expected behaviour:

There should be an sm-a736b, and the settings have the original model, but in applications it is completely different. 
![Screenshot_20240630_232958_Device Info HW](https://github.com/salvogiangri/UN1CA/assets/73845574/a23c0369-1644-41f7-b1ce-47132cda4610)
![Screenshot_20240630_232950_Settings](https://github.com/salvogiangri/UN1CA/assets/73845574/eab0e706-48bd-4661-9186-6f735ff8844f)

### Actual behaviour:

It's not sm-a736b, it's sm-s911b

### Logs:

-

**Comment by salvogiangri** [comment]
This is not a bug, the ROM is based on the Galaxy S23 firmware so it will be recognized as such system-wide. The Settings app shows the real device model number on purpose.
