### ISSUE TITLE
Quick settings instant acces option and notification bar lags a lot when you bring it down

### ISSUE THREAD

**Issue by spyzenen** [salvogiangri/UN1CA#118]
### UN1CA version:

Latest provided for A71, 2.0

### Device name:

Samsung Galaxy A71

### Device model number:

SM-A715F/DS

### Magisk/KernelSU version:

Latest magisk/integrity fix

### Steps to reproduce:

.

### Expected behaviour:

Be smooth

### Actual behaviour:

Lags

### Logs:

.

**Comment by salvogiangri** [comment]
Not enough details/no logs provided.

**Comment by spyzenen** [comment]
Wtf details do you want, i did told you the problem 😂
